### ISSUE TITLE
pymongo exception in cephprobe

### ISSUE THREAD

**Issue by laggeduout** [inkscope/inkscope#87] opened 2016-09-08 15:45 UTC
We noticed the below in the cephprobe log:

Exception AttributeError: "'Cursor' object has no attribute '_Cursor__id'" in <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x7f6350061f90>> ignored
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 341, in process_osd_dump
    osd_in_db = db.osd.find({"or" : [{"lost": {'$exists' : False}}, {"lost": False}]}, fields = {"_id" : 1})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1137, in find
    return Cursor(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fields'
2016-09-08 16:35:56.422942 -- WARNING : process_osd_dump did not work :  __init__() got an unexpected keyword argument 'fields'
2016-09-08 16:35:56.491993 -- Process Status
172.27.166.68 - - [08/Sep/2016 16:35:56] "GET /api/v0.1/status.json HTTP/1.1" 200 -
2016-09-08 16:35:59.423223 -- Process OSDDump
172.27.166.68 - - [08/Sep/2016 16:35:59] "GET /api/v0.1/osd/dump.json HTTP/1.1" 200 -
Exception AttributeError: "'Cursor' object has no attribute '_Cursor__id'" in <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x7f6350061f90>> ignored

I have tried removing all data in mongo and this does not seem to help.

The ceph cluster is jewel.

The package in use is:
inkscope-cephprobe                   1.4.0-2

Any hints on where to look?

**Comment by A-Dechorgnat** [comment] 2016-09-08 16:12
May be the version of pymongo that must be 2.x

**Comment by laggeduout** [comment] 2016-09-08 16:58
You are correct, I had to downgrade from 3.X to to 2.X - it seems ubuntu 16.04 packages ship 3.X.
2.X was found with python-pip
I also dropped the mongo data but there is one further error raising its head:

Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 277, in process_status
    monneti = db.net.find_one({"$where":  "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1084, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1149, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1081, in _refresh
    self.__codec_options.uuid_representation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1023, in __send_message
    self.__compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 144, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''192.168.0.1'

**Comment by laggeduout** [comment] 2016-09-09 11:21
I found this was caused by the mon's not having sysprobe installed.

**Comment by A-Dechorgnat** [comment] 2016-09-20 14:43
could we close this one?

**Comment by laggeduout** [comment] 2016-09-20 14:49
I would say so

**Comment by A-Dechorgnat** [comment] 2016-09-20 14:59
ok thanks

**Closed by A-Dechorgnat** 2016-09-20 14:59 UTC

**Comment by Floink99** [comment] 2017-01-20 09:59
Hi, 

it seems that i'm having the same problem. Can you tell us  the version of pymongo you're using please (or a pip list extract). I already downgrade pymongo but still have the issue. 

Thanks in advance. :)

**Comment by ghisl1** [comment] 2017-01-20 10:06
Hi,

here is the result of pip freeze 
pymongo==2.7

brgds

**Comment by Floink99** [comment] 2017-01-20 10:43
Thank you Ghisl1. 
I tried this version, drop the database, deploy sysprobe on mons, but i still have the issue. (the last one in logs it seems...) : 
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 277, in process_status
    monneti = db.net.find_one({"$where": "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 713, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 109, in _unpack_response
    error_object)
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''MYIPADDRESS''

i'm missing something (according to ubuntu 16.04 and embedded module/lib ?! ). and The dashboard inkscope does'nt show me all information like global status or ceph health. 

Kind regards.

**Comment by ghisl1** [comment] 2017-01-20 11:57
Hum...
Can you copy/paste the inkscope.conf?

brgds

**Comment by Floink99** [comment] 2017-01-20 12:02
here it is : 
{
    "ceph_conf": "/etc/ceph/ceph.conf",
    "ceph_rest_api": "SERVERA:8080",
    "ceph_rest_api_subfolder": "ceph_rest_api",
    "mongodb_host" : "SERVERB",
    "mongodb_set" : "mongodb0:27017,mongodb1:27017,mongodb2:27017",
    "mongodb_replicaSet" : "replmongo0",
    "mongodb_read_preference" : "ReadPreference.SECONDARY_PREFERRED",
    "mongodb_port" : 27017,
    "mongodb_user":"inkscope",
    "mongodb_passwd":"test",
    "is_mongo_authenticate" : 0,
    "is_mongo_replicat" : 0,
    "influxdb_endpoint":"http://inkscope_host:8096",
    "cluster": "ceph",
    "platform": "Jewel",
    "status_refresh": 3,
    "osd_dump_refresh": 3,
    "pg_dump_refresh": 60,
    "crushmap_refresh": 60,
    "df_refresh": 60,
    "cluster_window": 1200,
    "osd_window": 1200,
    "pool_window": 1200,
    "mem_refresh": 60,
    "swap_refresh": 600,
    "disk_refresh": 60,
    "partition_refresh": 60,
    "cpu_refresh": 30,
    "net_refresh": 30,
    "mem_window": 1200,
    "swap_window": 3600,
    "disk_window": 1200,
    "partition_window": 1200,
    "cpu_window": 1200,
    "net_window": 1200,
    "inkscope_root" : "SERVERA:8080",
    "radosgw_url": "http://SERVERA:7480",
    "radosgw_admin": "admin",
    "radosgw_key": "access-key",
    "radosgw_secret": "secret-key"
}

best regards

**Comment by ghisl1** [comment] 2017-01-20 12:28
It seems OK
Did you have a look at issue#43 ?

**Comment by Floink99** [comment] 2017-01-20 16:08
I saw it and modify the code. But things still goes wrong. 
i'm having this error : 
 database error: TypeError: Cannot read property 'addr' of null near 'll && this.inet.addr '

I see that Process OSDDumps is working well, But Process Status is not working. 


I reinstall Mon just to be sure. 
A ceph --cluster=ceph --admin-daemon /var/run/ceph/ceph-mon.MON1.asok mon_status 
show me that everything is good on each server. 

I suppose this is not just a warning and is probably the cause of missing data on the mainpage. 


Thx

**Comment by Floink99** [comment] 2017-01-27 12:39
Hi, 
I followed this one and drop the db.collection [#48](https://github.com/inkscope/inkscope/issues/48) 

Everything is fine

Cheers
