### ISSUE TITLE
InkScope Status is not Available

### ISSUE THREAD

**Issue by chencaijin** [inkscope/inkscope#82] opened 2016-07-21 07:28 UTC
Couldn't read monitor, osd ???

![default](https://cloud.githubusercontent.com/assets/17511013/17014565/b6c5d574-4f57-11e6-9a11-34bd9dd862f8.JPG)

**Comment by A-Dechorgnat** [comment] 2016-07-21 07:46
As I see, your installation is not complete:
- Status not available indicate there is no response from Ceph rest api ( please see http://inkscope.blogspot.fr/2015/03/inkscope-and-ceph-rest-api.html  and verify )
- Logged as "nothing" indicates there is an issue with your mongodb database or python dependencies ( please look at logs at /var/logs/inkscope )

**Comment by chencaijin** [comment] 2016-07-21 09:05
I couldn't download InkScope by this way:
Create /etc/apt/sources.list.d/inkscope.list and add line: 
deb https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS ./ 
Then 
apt-get update 

when I run apt-get update it would show error..
so, I tried to download by using wget all elements of inkscope

wget https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/inkscope-admviz_1.4.0.2.deb
wget https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/inkscope-cephprobe_1.4.0.2.deb
wget https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/inkscope-sysprobe_1.4.0.2.deb
wget https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/inkscope-common_1.4.0.2.deb
wget https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/inkscope-cephrestapi_1.4.0.2.deb
wget https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/inkscope-monitoring_1.4.0.2.deb

after that using sudo dpkg -i  to installed the debian files.

but there is no inkscopeprobe.conf file in the /opt/inkscope/etc/...
there was only inkscope.conf file at there...

any solution for this?

**Comment by chencaijin** [comment] 2016-07-21 09:11
![pic1](https://cloud.githubusercontent.com/assets/17511013/17017466/ffaf09f0-4f65-11e6-9b6c-4e1c83d793c9.JPG)

![pic3](https://cloud.githubusercontent.com/assets/17511013/17017504/24c4941c-4f66-11e6-8c31-0f51a037186e.JPG)

sudo apt-get update
![pic2](https://cloud.githubusercontent.com/assets/17511013/17017471/029b8206-4f66-11e6-94e8-6a87a3c26038.JPG)

**Comment by A-Dechorgnat** [comment] 2016-07-21 12:41
It could be a network problem, see  #76

**Comment by chencaijin** [comment] 2016-07-21 14:11
Hello Dechorgnat,
If I have ceph 1 deploy, 1 mon and 2 osd,
Could I all element of Inkscopes are installed in monitor server? or I should split to new server..
How many server that i have to prepare, because after I installed sysprobe, the service is not stable...
I monitor the status for first time, there was a pid after a few minute the status become sysprob daemon. no pid.  what's element that i have to install in monitor, osd and new server..help to explain pls thank you Decho..

**Comment by A-Dechorgnat** [comment] 2016-07-22 08:13
That means that probably probes are not working correctly.
Take a look at /var/logs/inkscope for cephprobe.log and sysprobe.log

**Comment by chencaijin** [comment] 2016-07-22 08:45
Hello Decho,
in /etc/mongodb.conf
I set : 
bind_ip = 0.0.0.0
port = 27107 based on some references web

and then 
inkscope.conf
"ceph_conf": "/etc/ceph/ceph.conf",
    "ceph_rest_api": "192.168.244.141:5000",
    "ceph_rest_api_subfolder": "ceph_rest_api",
    "mongodb_host" : "192.168.244.144",
    "mongodb_set" : "mongodb0:27017,mongodb1:27017,mongodb2:27017",
    "mongodb_replicaSet" : "replmongo0",
    "mongodb_read_preference" : "ReadPreference.SECONDARY_PREFERRED",
    "mongodb_port" : 27017,
    "mongodb_user":"ceph",
    "mongodb_passwd":"monpassword",

 "radosgw_url": "192.168.244.141:7480",
    "radosgw_admin": "inkscope",
    "radosgw_key": "inkscopeAccess",
    "radosgw_secret": "inkscopeSecret"

cephprobe.log:
2016-07-05 23:35:21.732256
SysProbe loading
cluster =  ceph
cephConf =  /etc/ceph/ceph.conf
fsid =  ab539bc3-c61a-4e6d-860b-510592e532c7
hb_refresh =  5
mem_refresh =  60
mem_window =  1200
swap_refresh =  600
swap_window =  3600
disk_refresh =  60
disk_window =  1200
partition_refresh =  60
partition_window =  1200
cpu_refresh =  30
cpu_window =  1200
net_refresh =  30
net_window =  1200
process_refresh =  60
process_window =  1200
mongodb_host =  192.168.244.144
mongodb_port =  27017
is_mongo_replicat =  0
mongodb_set =  'mongodb0:27017,mongodb1:27017,mongodb2:27017'
mongodb_replicaSet =  replmongo0
mongodb_read_preference =  ReadPreference.SECONDARY_PREFERRED
is_mongo_authenticate 0
mongodb_user =  ceph
mongodb_passwd =  monpassword
version psutil =  4  ( 4.3.0 )
hostname =  mon1
no replicat set
no authentication
Traceback (most recent call last):
  File "sysprobe.py", line 845, in <module>
    daemon.start()
  File "/opt/inkscope/bin/daemon.py", line 87, in start
    self.run()
  File "sysprobe.py", line 745, in run
    HWdisks, partitions, HWnets, HWcpus = init_host(hostname, db)
  File "sysprobe.py", line 378, in init_host
    db.disks.update({'_id': d['_id']}, d, upsert=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2242, in update
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 762, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 192.168.244.144:27017: [Errno 111] Connection refused

What should i do?

Thank you Decho

**Comment by A-Dechorgnat** [comment] 2016-07-22 09:22
Try to comment "bind_ip = 0.0.0.0"

**Comment by chencaijin** [comment] 2016-07-26 05:34
same error... "some osd stats are missing"

**Comment by chencaijin** [comment] 2016-07-26 05:35
do you have completed installation step that easier to understand?

**Comment by Dechorgnat** [comment] 2016-07-26 07:54
Same error in logs?

2016-07-26 7:35 GMT+02:00 chencaijin <notifications@github.com>:

**Comment by chencaijin** [comment] 2016-07-26 08:02
yes the same error, i don't know why. Your manual installation step can't be run well.
I had tried more than ten times, do you have more clear installation step..
example you have how many server (deploy, monitor, osd1, osd2) and then next step...more detail..

**Comment by chencaijin** [comment] 2016-07-26 08:35
userceph@mon1:~$ sudo /etc/init.d/ceph-rest-api start
Starting ceph-rest-api python server
userceph@mon1:~$  * Running on http://0.0.0.0:5000/
Traceback (most recent call last):
  File "/usr/bin/ceph-rest-api", line 67, in <module>
    app.run(host=app.ceph_addr, port=app.ceph_port)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 710, in run_simple
    inner()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 692, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 486, in make_server
    passthrough_errors, ssl_context)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 410, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by chencaijin** [comment] 2016-07-26 09:20
Hi Decho,
It can be run.. There is no error again, i have wrong path. Thank you very much.

**Comment by Dechorgnat** [comment] 2016-07-26 10:05
Very good news

**Comment by gittygoo** [comment] 2016-08-17 23:49
The documentation is quite  a mess, we have to get bits and bobs from multiple pages... i am facing the same problems...

**Comment by chengweiv5** [comment] 2016-09-07 07:16
inscope is awesome, it's better is we have more documents, I have fight two days before I have everything works with ceph jewel.

As you can think, read a lot of code.

**Comment by Dechorgnat** [comment] 2016-09-07 07:53
Thank you
I've planned to refactor the documentation in the next weeks.

2016-09-07 9:16 GMT+02:00 Chengwei Yang <notifications@github.com>:

**Comment by chengweiv5** [comment] 2016-09-07 14:36
I think https://github.com/inkscope/inkscope/pull/85 fix this issue, verified on jewel with only mons and osds configured.

**Comment by A-Dechorgnat** [comment] 2016-09-08 16:25
#85 merged

**Closed by A-Dechorgnat** 2016-09-08 16:25 UTC

**Comment by dohainam** [comment] 2017-04-22 09:59
Dear Mr Dechorgnat 

I am facing same problem in this case. When i see cephprobe.log I see the problem is authenticate between app and mongodb. Can you help me how to setup mongodb, what is database name, what is user to access database

P/S. I attached some log file and attached file. 

Thanks for your support 
[webserver_error.zip](https://github.com/inkscope/inkscope/files/948882/webserver_error.zip)
[cephprobe.txt](https://github.com/inkscope/inkscope/files/948878/cephprobe.txt)
[inkscope.txt](https://github.com/inkscope/inkscope/files/948879/inkscope.txt)

**Comment by A-Dechorgnat** [comment] 2017-04-24 08:39
`Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 874, in <module>
    daemon.start()
  File "/opt/inkscope/bin/daemon.py", line 87, in start
    self.run()
  File "/opt/inkscope/bin/cephprobe.py", line 783, in run
    client = MongoClient(mongodb_host, mongodb_port)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 337, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: could not connect to 10.55.53.48:27017: [Errno 111] Connection refused`

This could be a problem with mongo config and bind_ip parameter.
